# config/packages/security.yaml
security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            access_denied_url: /access-denied
            provider: app_user_provider
            anonymous: ~
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home # specify the default target path here
            logout:
                path: app_logout
                target: app_home

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: /profile, roles: ROLE_USER }
