vich_uploader:
    db_driver: orm

    mappings:
        user_images:
            uri_prefix: '%app.path.user_path%'
            upload_destination: '%kernel.project_dir%/public%app.path.user_path%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
